[오리] 4월 7일 계획
woowacourse-study/2022-daily-planner pull request #243
Opened 2022-04-06 22:13 UTC by jinyoungchoi95

생활패턴이 망했네요 :(

### 4월 7일(목)
- [ ] 체스 피드백 pr
- [ ] 저녁 회식
- [ ] 휴식

2022-04-06 23:35 UTC, al-bur approved these changes
오리 홧팅입니다!

2022-04-07 06:57 UTC, leo0842 approved these changes
파랑과 재미지게 놀다 오세요~!!

2022-04-07 06:57 UTC, hamcheeseburger approved these changes
회식과 휴식 🏖 🌀

2022-04-08 14:06 UTC, hamcheeseburger requested changes
이건 언제 머지 되나요?ㅋㅋㅋㅋㅋㅋㅋ

2022-04-08 17:01 UTC, merged