[오리] 5월 10일 계획
woowacourse-study/2022-daily-planner pull request #351
Opened 2022-05-09 23:03 UTC by jinyoungchoi95

오늘부터 알차게 살아가기 🔥 

### 5월 4일(화)
- [x] 요가 1시간
- [ ] 알고리즘 2문제
- [ ] 오전 강의 + 말하기

- [ ] 오후 강의 들었던거 리마인드 겸 정리 (~8:00)
- [ ] ~섹션 7 (~10:00)
- [ ] 리뷰 오면 반영

2022-05-09 23:59 UTC, summerlunaa requested changes
면담 신청하기 > 안 하면 빡빡이

2022-05-10 00:30 UTC, Yboyu0u approved these changes
> 요가??!!!
> 한 수 가르쳐 주시죠

https://edu.nextstep.camp/c/9rVorOQ3/
다음 기수 ㄱㄱ

2022-05-10 00:34 UTC, al-bur approved these changes
오~ 이전보다 더 구체적입니다👍👍👍

2022-05-10 01:24 UTC, Hyunta approved these changes
시간대별로 적혀있어서 너무 좋네요
아침 요가까지 부지런합니다👍🏻

2022-05-10 01:33 UTC, leo0842 approved these changes
알찬 하루 응원합니다

2022-05-10 01:40 UTC, jswith approved these changes
오리 요가하는 모습 우테코 브이로그 ㄱㄱ

2022-05-10 02:07 UTC, summerlunaa approved these changes

2022-05-10 17:22 UTC, merged