[오리] 5월 18일 계획
woowacourse-study/2022-daily-planner pull request #408
Opened 2022-05-17 23:40 UTC by jinyoungchoi95

멘탈나간 이틀 후 오늘부터 차분하게 돌아오는 기분 🚗

### 5월 18일(수)
- [ ] 알고리즘 2문제
- [ ] 피드백오면 반영 / 머지되면 2단계
- [ ] 스프링 db강의 1섹션
- [ ] 영화보기

2022-05-17 23:47 UTC, jswith requested changes
무슨 영화? 👀

> 범죄도시 2 😆

2022-05-18 00:00 UTC, jswith approved these changes

2022-05-18 01:35 UTC, summerlunaa approved these changes
어제 개봉인줄 알았던 범죄도시,,, PR 제출한 자의 여유군요

2022-05-18 01:37 UTC, Hyunta approved these changes
머지되면 2단계 (PR) 이라는 말인가요 오리?

2022-05-18 06:41 UTC, leo0842 approved these changes
닥터 스트레인지2 추천 👍

2022-05-18 12:43 UTC, merged