[앨버] 7월 5일 계획
woowacourse-study/2022-daily-planner pull request #579
Opened 2022-07-05 01:19 UTC by al-bur

- [ ] 프로젝트 진행

2022-07-05 01:39 UTC, summerlunaa requested changes
?????

2022-07-05 10:21 UTC, Yboyu0u requested changes
??!!!!!!!!!!!!!!!!!!!!!띵

2022-07-05 14:19 UTC, al-bur commented
다들 죄송합니다...계획 세세하게 적을게요..

2022-07-05 14:24 UTC, jinyoungchoi95 approved these changes
앞으로 열심히하세요

2022-07-05 14:38 UTC, summerlunaa approved these changes

2022-07-06 01:05 UTC, jswith approved these changes

2022-07-06 01:06 UTC, merged